endpoints for getting AppConfigs
webperside/course-erp-backend pull request #111
Opened 2023-10-16 14:46 UTC by ttayping

what i did:
1) payload model for AppConfig (fields: String value; String description)
2) getting methods (findById and getAll) in controller layer 
3) entity mapper interface which include methods transfer data from entity to payload
4) edit return type and parameter of getting methods in Service layer

2023-10-16 20:07 UTC, gadirovakhadija approved these changes

2023-10-19 06:31 UTC, hamidsultanzadeh requested changes

2023-10-19 11:23 UTC, ttayping commented
I think that we don't need business layer only for mapping stuff. That's why mapping procedure placed in the Controller layer.

2023-10-19 20:47 UTC, hamidsultanzadeh approved these changes

2023-10-19 20:47 UTC, merged