Feat #4 crud services for countries table
webperside/course-erp-backend pull request #12
Opened 2023-08-31 20:55 UTC by aytiqaqash

Please review and merge these changes if everything is fine.

2023-09-01 18:43 UTC, farhadnajafov approved these changes

2023-09-07 19:17 UTC, hamidsultanzadeh requested changes
please fix the issues mentioned in comments

2023-09-07 19:17 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/repository/CountryRepository.java
> +    void update(@RequestBody Country country);
Remove @RequestBody from the repository's method

2023-09-07 19:17 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/services/country/CountryService.java
> +    void update(@RequestBody Country country);
same

2023-09-08 10:40 UTC, hamidsultanzadeh approved these changes

2023-09-08 10:40 UTC, merged