creating model class, repository, service class, mapper for language …
webperside/course-erp-backend pull request #15
Opened 2023-09-01 10:46 UTC by farhadnajafov

…table

2023-09-01 18:33 UTC, aytiqaqash approved these changes
LGTM

2023-09-07 19:19 UTC, hamidsultanzadeh requested changes
please fix the issues mentioned in comments

2023-09-07 19:19 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/repository/LangugaeRepository.java
> +    void update(@RequestBody Language language);
Remove @requestbody from the repository's method

2023-09-07 19:19 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/services/language/LanguageService.java
> +    void update (@RequestBody Language language);
same

2023-09-08 10:39 UTC, hamidsultanzadeh approved these changes

2023-09-08 10:39 UTC, merged

2023-09-08 17:30 UTC, aytiqaqash reviewed
LGTM