creating model class, repository, service class and mapper for subject
webperside/course-erp-backend pull request #17
Opened 2023-09-02 18:35 UTC by farhadnajafov

2023-09-03 16:09 UTC, aytiqaqash requested changes
We are using camel cases in Model classes based on the name convention and suggesting changing "course_id" and "language_id" to "courseId" and "languageId" accordingly. Could you please change the Mapper file as well?

2023-09-04 14:45 UTC, farhadnajafov commented
> We are using camel cases in Model classes based on the name convention and suggesting changing "course_id" and "language_id" to "courseId" and "languageId" accordingly. Could you please change the Mapper file as well?

@aytiqaqash I changed. Please review agin

2023-09-04 21:19 UTC, aytiqaqash approved these changes
LGTM

2023-09-07 19:21 UTC, hamidsultanzadeh requested changes

2023-09-07 19:21 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/services/subject/SubjectService.java
> +    void update (@RequestBody Subject subject);
Remove @requestbody from the repository's method

2023-09-07 19:21 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/repository/SubjectRepository.java
> +    void update (@RequestBody Subject subject);
Remove @requestbody from the repository's method

2023-09-08 10:38 UTC, merged

2023-09-08 17:31 UTC, aytiqaqash reviewed
LGTM