creating add/update endpoints for languages
webperside/course-erp-backend pull request #37
Opened 2023-09-13 12:15 UTC by farhadnajafov

2023-09-13 18:33 UTC, hamidsultanzadeh requested changes

2023-09-15 02:40 UTC, aytiqaqash requested changes
I believe "/languages" should be in the RequestMapping("/v1/languages") annotation. For the post request insert method, the route should be "/language" for the (put) update method it should be "/language/{id}".

2023-10-01 06:04 UTC, hamidsultanzadeh approved these changes

2023-10-01 06:04 UTC, hamidsultanzadeh commented
@aytiqaqash please leave your decision

2023-10-01 16:15 UTC, aytiqaqash approved these changes
LGTM

2023-10-01 16:17 UTC, merged