user-configs table added
webperside/course-erp-backend pull request #38
Opened 2023-09-13 16:40 UTC by ArabkhanDev

2023-09-13 18:35 UTC, hamidsultanzadeh requested changes

2023-09-13 18:35 UTC, hamidsultanzadeh commented on src/main/resources/migrations/1.0/1.1.3-user-configs-table.xml
> +            <column name="key" type="VARCHAR(50)">
rename this column to id

2023-09-14 09:53 UTC, hamidsultanzadeh commented on src/main/resources/migrations/1.0/1.1.3-user-configs-table.xml
> +            <column name="description" type="VARCHAR(50)">
and also please remove description column from the table.
and move id column to the first position

2023-09-14 10:01 UTC, hamidsultanzadeh approved these changes

2023-09-14 10:03 UTC, hamidsultanzadeh commented
@farhadnajafov please review this PR whenever you are available

2023-09-14 12:48 UTC, farhadnajafov approved these changes

2023-09-14 21:15 UTC, merged