Feat #31 add endpoint for subjects
webperside/course-erp-backend pull request #39
Opened 2023-09-13 18:21 UTC by MuradAbbaszade

Endpoint added

2023-09-13 18:40 UTC, hamidsultanzadeh commented
please, look at the comments and fix them

use business service for inserting process.
create new method for checking existence of language, like isExist (look at UserService)

2023-09-13 18:43 UTC, hamidsultanzadeh requested changes

2023-09-13 18:43 UTC, hamidsultanzadeh commented on docker-compose.yml
keep this file unchanged

2023-09-15 02:32 UTC, aytiqaqash requested changes
Based on my knowledge, the best practices of REST API verbs should not be in the route. Instead of "/add" suggesting name "/subject". So it will be POST a subject.

2023-09-15 17:54 UTC, aytiqaqash approved these changes
LGTM

2023-09-17 07:28 UTC, hamidsultanzadeh approved these changes

2023-09-17 07:28 UTC, merged