Feat #49 add edit endpoints for groups
webperside/course-erp-backend pull request #55
Opened 2023-09-27 13:55 UTC by ttayping

in this branch I created Controller, mapper and payload model for Group, add and update methods.

2023-09-27 17:21 UTC, gadirovakhadija requested changes

2023-09-27 17:21 UTC, gadirovakhadija commented on src/main/java/com/webperside/courseerpbackend/models/payload/group/GroupPayload.java
we dont need @Getter @Setter in here

2023-09-27 17:21 UTC, gadirovakhadija commented on src/main/java/com/webperside/courseerpbackend/controller/GroupController.java
You must do all work in Service Layer .You just call service components in your controller class.

2023-09-27 17:21 UTC, gadirovakhadija commented on pom.xml
please follow codes in main project (for student or subject)

2023-09-27 17:23 UTC, gadirovakhadija commented on src/main/java/com/webperside/courseerpbackend/controller/GroupController.java
please follow codes in main project (for student or subject)

2023-09-28 07:37 UTC, ttayping commented on src/main/java/com/webperside/courseerpbackend/controller/GroupController.java
we get agreement about where mapper procedure must be happen. Final decision is controller class for this case.

2023-09-28 11:07 UTC, hamidsultanzadeh requested changes

2023-09-28 11:07 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/controller/GroupController.java
> +    private static final GroupEntityMapper groupEntityMapper =GroupEntityMapper.INSTANCE;
You don't need to store INSTANCE value of Mapper separately. it is unnecessary. use it directly . f.e
GroupEntityMapper.INSTANCE.toEntity()

2023-10-01 06:05 UTC, hamidsultanzadeh approved these changes

2023-10-01 06:06 UTC, hamidsultanzadeh commented
@aytiqaqash @gadirovakhadija please leave your decision

2023-10-01 07:10 UTC, gadirovakhadija approved these changes

2023-10-01 07:15 UTC, merged