Added isValid method and test of its class
webperside/course-erp-backend pull request #95
Opened 2023-10-11 16:14 UTC by gadirovakhadija

Write isValid method an test class of it. In the test class I have some problems for just isValid's test method. please look isValid class first if its ok I'll do correct test class for it.

2023-10-11 16:37 UTC, hamidsultanzadeh requested changes

2023-10-11 16:37 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/exception/OTPValidationException.java
we don't need that. we already have BaseException. You just need to add new enum on ErrorEnum

2023-10-11 16:37 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/utils/OTPUtils.java
>  public class OTPUtils {
add here @Component for triggering spring DI

2023-10-11 16:37 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/utils/OTPUtils.java
> +    public static void setRedisService(RedisService service){
and also add a constructor for injecting RedisService. and take the injected value and set it to the static redis service. we did similar code block on PrivatePublicKeyUtils

2023-10-11 16:37 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/utils/OTPUtils.java
> +    public static void setRedisService(RedisService service){
so you don't need this set method

2023-10-11 16:37 UTC, hamidsultanzadeh commented on src/main/java/com/webperside/courseerpbackend/utils/OTPUtils.java
> +            throw new OTPValidationException(OTPValidationResult.OTP_IS_NOT_VALID);
throw our exception

2023-10-11 16:37 UTC, hamidsultanzadeh commented on pom.xml
> +		<mockito-core.version>3.11.2</mockito-core.version>
if not mistaken, we don't need these dependencies as well. because they have to be come with starter dependency of test

2023-10-13 08:02 UTC, hamidsultanzadeh approved these changes

2023-10-14 03:58 UTC, aytiqaqash approved these changes
LGTM

2023-10-15 07:46 UTC, merged